version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/code
    command: npm run build
    command: npm start
  proxy:
    image: nginx:1.11
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
